spring:
  main:
    banner-mode: off

  datasource:
    username: docker
    password: mysql_very_secret_docker_password
    url: jdbc:mysql://docker-mysql:3306/cosmere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: cosmere-pool
      maximum-pool-size: 5

  flyway:
    default-schema: cosmere
    driver-class-name: ${spring.datasource.driver-class-name}
    placeholders:
      alter-column: MODIFY

  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: "/api"
