spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
