spring:
  main:
    banner-mode: off

  datasource:
    username: docker
    password: mysql_very_secret_docker_password
    url: jdbc:mysql://docker-mysql:3306/cosmere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: cosmere-db-pool
      maximum-pool-size: 5

  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        default_schema: cosmere
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    default-schema: cosmere

server:
  servlet:
    context-path: "/api"
