DROP DATABASE IF EXISTS cosmere;
DROP USER IF EXISTS `docker`@`%`;
CREATE DATABASE IF NOT EXISTS cosmere CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `docker`@`%` IDENTIFIED WITH mysql_native_password BY 'mysql_very_secret_docker_password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `cosmere`.* TO `docker`@`%`;
